access_token: 7dd3a1b523590401b2bcf7a2f78bd54d361c884e2a7788d863cd679569afcd06fd1b7c80c8b7fff0d5e12
group_id: 201009728

server:
  port: 5556

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pubsub
    username: postgres
    password: root
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.vk.api.sdk.httpclient: error
#  file:
#    name: log.txt
